server:
  port: 8081

spring:
  application:
    name: mentee-power-crm
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

gg:
  jte:
    template-location: ./src/main/resources/jte
    development-mode: true
    usePrecompiledTemplates: false
    suffix: .jte