server:
  port: 8081

spring:
  application:
    name: mentee-power-crm


gg:
  jte:
    template-location: ./src/main/resources/jte
    development-mode: true
    usePrecompiledTemplates: false
    suffix: .jte