server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  application:
    name: mentee-power-crm
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
gg:
  jte:
    template-location: ./src/main/resources/jte
    development-mode: true
    usePrecompiledTemplates: false
    suffix: .jte

# Внешние API
email:
  validation:
    base-url: ${EMAIL_VALIDATION_URL:http://localhost:8089}